# Generated by Django 3.2.4 on 2021-08-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='size',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
